### ISSUE TITLE
v2.0.0 discussion

### ISSUE THREAD

**Issue by Morgul** [Morgul/trivialdb#23]
This is a major change for Trivialdb, and one I feel has been needed for a while.

The vast majority of bugs in the system have come from the Models API, and it has felt that while nifty, the Model system is weighing down the core of TrivialDB down. So, the decision has been made to split the projects into the following:

* TrivialDB - a simple, fast, in-memory database.
* TrivialModels - an elegant, promise-based model API.

When we make the split, I would also like to make the following changes:

* Switch to lodash's [lazy evaluation](http://filimanjaro.com/blog/2014/introducing-lazy-evaluation/) API (huge performance increase)
* Add `Collection` support (So we would have collections, which contain stores)
* Ensure TrivialDB is a singleton (so that no matter what path your code requires, it all returns the same instance. @whitelynx, you should have code for this?)
* (maybe) Add RethinkDB-like [changefeed](https://rethinkdb.com/docs/changefeeds/javascript/) support?

There may be some more features we want to add; anyone have any thoughts?

/cc: @boneskull - Since you seem to use this, thought you might have some thoughts.

**Comment by boneskull** [comment]
I'm just looking for a sane way to persist data to a `.json` file.  I'd be happy with splitting it up.

Regarding these models, since we're just talking about JSON datastores, [Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) could be leveraged to persist all properties via `set()`, and to retrieve from the store upon `get()`.  Validation could come in the form of [Joi](https://www.npmjs.com/package/joi), which could be simplified again w/ Proxies.  
Combine this with something like [stampit](https://www.npmjs.com/package/stampit), and you can create models via composition.

My point being: I'm not sure why I'd want to use the Models API.  "Do one thing and do it well", etc.  If I need some of the functionality that Models provide, I'll probably reach for one of the tools above.

In my mind, the "trivial" part of TrivialDB is the bread-and-butter of this module.  Hope this is good feedback and you are not offended.

> Ensure TrivialDB is a singleton (so that no matter what path your code requires, it all returns the same instance. @whitelynx, you should have code for this?)

I assume this means if you try to open the same path in two separate modules, you get the same instance back--not that you are locked into one "root path".

But in general, when I think about new features I ask, "am I gonna need it?"  What's driving these?

**Comment by Morgul** [comment]
That's great feedback. :)

In short, I pretty much agree with your points. As for the particular technologies, there's some pros/cons (like, for example, node doesn't yet support Proxies) but over all I feel it's important to keep things slim and composable. (I will be checking out some of those projects to see how it will fit with Models.)

> I assume this means if you try to open the same path in two separate modules, you get the same instance back--not that you are locked into one "root path".

Yes, same instance. If I add Collections, it'll be one root path per collection. (I need this feature in a project I'm working on, which is why I'll probably add it soon.)

Most of the features I've added have been things I've needed/wanted for personal projects. It's why the Models API even existed in the first place; I wanted it, so I added it. But, as you said, "do one thing and do it well". I think this change will be a very positive one for TrivialDB.
